[package]
name = "sqliteml"
version = "0.0.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.17", features = ["auto-initialize"] }
serde_json = "1.0.95"
sqlite-loadable = "0.0.5"
sqlite3_ext = "0.1.3"

[build-dependencies]
cbindgen = "0.24.3"

[lib]
crate-type=["cdylib"]
